on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to activate a workflow
    steps:
    - uses: kedoska/invoke-paragon-action@master
      with:
          repository: ${{ github.repository }}
          status: "completed"
