on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to activate a workflow
    steps:
    - name: Invoke Paragon Endpoint
      uses: kedoska/invoke-paragon-action@v1
      with:
          repository: ${{ github.repository }}
          status: "completed"
      env:
        PARAGON_WORKFLOW_ID: ${{ secrets.PARAGON_WORKFLOW_ID }}
