on: [push]

jobs:
  hello_paragon:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke Paragon Endpoint
      uses: kedoska/invoke-paragon-action@v1
      with:
          param1: "first param"
          param2: "second static param"
          param3: ${{ github.repository }}
      env:
        PARAGON_WORKFLOW_ID: ${{ secrets.PARAGON_WORKFLOW_ID }}